Repository Lawnmower-416/Lawnmower, pull requests merged in 2022-11, with the labels that each got.

#238 Feature-nodemailer
  client/src/auth/index.js
  client/src/components/screens/LoginScreen.js
  client/src/components/screens/PasswordChange.js
  client/src/requests/auth-request.js
  server/controllers/auth-controller.js
  server/models/user-schema.js
  server/package.json
  server/routes/auth-router.js
Labels: build 4

#247 Undo/Redo Tileset Functionality
  client/src/components/screens/editor/TileEditor.js
  client/src/components/screens/editor/TileSidebar.js
  client/src/components/screens/editor/Toolbar.js
  client/src/editor/index.js
  client/src/requests/tileset-editor-api.js
  client/src/transactions/BulkTileChangeTransaction.js
  client/src/transactions/TileEditTransaction.js
  client/src/transactions/Transaction.js
  client/src/transactions/jsTPS.js
Labels: build 4

#246 Feature-cicd automation tests for BE
  .github/workflows/testing.yml
  client/babel.config.js
  client/package.json
  client/src/App.test.old.js
  server/jest-mongodb-config.js
  server/jest.config.js
  server/models/comment-schema.js
  server/models/layer-schema.js
  server/package.json
  server/utils/__tests__/comment.test.js
  server/utils/__tests__/layer.test.js
  server/utils/__tests__/like.test.js
  server/utils/__tests__/map.test.js
  server/utils/__tests__/post.test.js
  server/utils/__tests__/property.test.js
  server/utils/__tests__/tags.test.js
  server/utils/__tests__/tileset.test.js
  server/utils/__tests__/user.test.js
Labels: build 4

#251 Change Tileset Name
  client/src/components/modals/TilesetSettingsModal.js
  client/src/editor/index.js
Labels: build 4

#255 Undo Changes from Previous Commits
  client/src/requests/index.js
  server/app.js
  server/controllers/auth-controller.js
  server/package.json
Labels: bug, build 5

#257 Refactor Build 4 Tileset Editor Code
  client/src/components/screens/editor/TileEditor.js
  client/src/editor/index.js
Labels: build 5

#262 Update-adding a verified screen and some verification setup
  client/src/auth/index.js
  client/src/components/modals/ErrorModal.js
  client/src/components/screens/PasswordChange.js
  client/src/requests/index.js
  client/src/requests/map-editor-api.js
  server/controllers/auth-controller.js
  server/models/user-schema.js
  server/routes/auth-router.js
Labels: build 5

#264 Feature map editor
  client/src/components/modals/ImportTilesetModal.js
  client/src/components/screens/MapEditor.js
  client/src/components/screens/editor/LayerSidebar.js
  client/src/components/screens/editor/MainEditor.js
  client/src/components/screens/editor/TileSidebar.js
  client/src/components/screens/editor/TilesetSidebar.js
  client/src/editor/index.js
  client/src/requests/map-editor-api.js
  server/auth/index.js
  server/controllers/AWSManager/AWSlayereditor-manager.js
  server/controllers/AWSManager/AWSmapeditor-manager.js
  server/controllers/AWSManager/AWSmongoose-manager.js
  server/controllers/AWSManager/AWStileseteditor-manager.js
  server/controllers/layer-editor-controller.js
  server/controllers/map-editor-controller.js
Labels: build 5

#265 Update-change password confirmation screen
  client/src/App.js
  client/src/auth/index.js
  client/src/components/screens/PasswordChangedScreen.js
  client/src/components/screens/VerifiedAccountScreen.js
  server/controllers/auth-controller.js
Labels: build 5

#267 Feature map editor
  client/src/components/screens/editor/LayerSidebar.js
  client/src/components/screens/editor/MainEditor.js
  server/controllers/AWSManager/AWSlayereditor-manager.js
Labels: build 5

#268 Cut/Copy/Paste
  client/src/components/screens/editor/MainEditor.js
  client/src/components/screens/editor/Toolbar.js
  client/src/editor/index.js
Labels: build 5

#269 Save Map
  client/src/components/screens/editor/Headerbar.js
  client/src/components/screens/editor/Toolbar.js
  client/src/editor/index.js
Labels: build 5
